# Generated by Django 5.2.5 on 2025-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
